name: Pre-Main-Post Action

inputs:
  usingEmoji:
    description: "Use emoji?"
    required: true
    type: boolean

  name:
    description: "Your name"
    required: false
    default: "GitHub Actions"

runs:
  using: "composite"
  steps:
    - name: Pre
      shell: bash
      run: |
        echo "Pre:"
        echo "name = ${{ inputs.name }}"
        echo "usingEmoji = ${{ inputs.usingEmoji }}"

    - name: No Explicit Equals
      if: ${{ inputs.usingEmoji }}
      shell: bash
      run: |
        echo "No Explicit Equals: ${{ inputs.usingEmoji }}"

    - name: Equals `'true'`
      if: ${{ inputs.usingEmoji == 'true' }}
      shell: bash
      run: |
        echo "Equals 'true': ${{ inputs.usingEmoji }} == 'true'"

    - name: Equals `'True'`
      if: ${{ inputs.usingEmoji == 'True' }}
      shell: bash
      run: |
        echo "Equals 'True': ${{ inputs.usingEmoji }} == 'True'"

    - name: Equals `true`
      if: ${{ inputs.usingEmoji == true }}
      shell: bash
      run: |
        echo "Equals true: ${{ inputs.usingEmoji }} == true"

    # Causes error: `Error: Unrecognized named-value: 'True'`
    # - name: Equals `True`
    #   if: ${{ inputs.usingEmoji == True }}
    #   shell: bash
    #   run: |
    #     echo "Equals True: ${{ inputs.usingEmoji }} == True"

    - name: Equals `'yes'`
      if: ${{ inputs.usingEmoji == 'yes' }}
      shell: bash
      run: |
        echo "Equals 'yes': ${{ inputs.usingEmoji }} == 'yes'"

    - name: Equals `'Yes'`
      if: ${{ inputs.usingEmoji == 'Yes' }}
      shell: bash
      run: |
        echo "Equals 'Yes': ${{ inputs.usingEmoji }} == 'Yes'"

    - name: Equals `'y'`
      if: ${{ inputs.usingEmoji == 'y' }}
      shell: bash
      run: |
        echo "Equals 'y': ${{ inputs.usingEmoji }} == 'y'"

    - name: Equals `'Y'`
      if: ${{ inputs.usingEmoji == 'Y' }}
      shell: bash
      run: |
        echo "Equals 'Y': ${{ inputs.usingEmoji }} == 'Y'"

    - name: Equals `1`
      if: ${{ inputs.usingEmoji == 1 }}
      shell: bash
      run: |
        echo "Equals 1: ${{ inputs.usingEmoji }} == 1"

    - name: Equals `0`
      if: ${{ inputs.usingEmoji == 0 }}
      shell: bash
      run: |
        echo "Equals 0: ${{ inputs.usingEmoji }} == 0"

    - name: Equals `null`
      if: ${{ inputs.usingEmoji == null }}
      shell: bash
      run: |
        echo "Equals null: ${{ inputs.usingEmoji }} == null"

    - name: Equals `'null'`
      if: ${{ inputs.usingEmoji == 'null' }}
      shell: bash
      run: |
        echo "Equals 'null': ${{ inputs.usingEmoji }} == 'null'"

    - name: Equals `''`
      if: ${{ inputs.usingEmoji == '' }}
      shell: bash
      run: |
        echo "Equals '': ${{ inputs.usingEmoji }} == ''"

    - name: Equals `'undefined'`
      if: ${{ inputs.usingEmoji == 'undefined' }}
      shell: bash
      run: |
        echo "Equals 'undefined': ${{ inputs.usingEmoji }} == 'undefined'"

    - name: Main
      shell: bash
      run: |
        echo "Main: Hello ${{ inputs.name }}!"

    - name: Post
      if: ${{ inputs.usingEmoji }}
      shell: bash
      run: |
        echo "Post: 👋 ${{ inputs.name }}!"