name: Weird boolean in GitHub Actions

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      boolValue:
        description: "Use emoji?"
        required: false
        default: y

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "boolValue: ${{ github.event.inputs.boolValue }}"
        if: ${{ github.event.inputs.boolValue != null }}
        uses: ./.github/actions/boolean-comparison
        with:
          boolValue: ${{ github.event.inputs.boolValue }}

      - name: "boolValue: true"
        uses: ./.github/actions/boolean-comparison
        with:
          boolValue: true

      - name: "boolValue: false"
        uses: ./.github/actions/boolean-comparison
        with:
          boolValue: false

      - name: "boolValue: True"
        uses: ./.github/actions/boolean-comparison
        with:
          boolValue: True

      - name: "boolValue: yes"
        uses: ./.github/actions/boolean-comparison
        with:
          boolValue: yes

      - name: "boolValue: Yes"
        uses: ./.github/actions/boolean-comparison
        with:
          boolValue: Yes

      - name: "boolValue: on"
        uses: ./.github/actions/boolean-comparison
        with:
          boolValue: on

      - name: "boolValue: On"
        uses: ./.github/actions/boolean-comparison
        with:
          boolValue: On

      - name: "boolValue: off"
        uses: ./.github/actions/boolean-comparison
        with:
          boolValue: off

      - name: "boolValue: Off"
        uses: ./.github/actions/boolean-comparison
        with:
          boolValue: Off

      - name: "boolValue: 1"
        uses: ./.github/actions/boolean-comparison
        with:
          boolValue: 1

      - name: "boolValue: 0"
        uses: ./.github/actions/boolean-comparison
        with:
          boolValue: 0

      - name: "boolValue: ''"
        uses: ./.github/actions/boolean-comparison
        with:
          boolValue: ""

      - name: "boolValue: null"
        uses: ./.github/actions/boolean-comparison
        with:
          boolValue: null

      - name: "boolValue: fromJson('[]')"
        uses: ./.github/actions/boolean-comparison
        with:
          boolValue: ${{ fromJson('[]') }}

      - name: "boolValue: fromJson('{}')"
        uses: ./.github/actions/boolean-comparison
        with:
          boolValue: ${{ fromJson('{}') }}

      - name: "boolValue: fromJson('false')"
        uses: ./.github/actions/boolean-comparison
        with:
          boolValue: ${{ fromJson('false') }}
