name: Greet Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      name:
        description: "Your name"
        required: false
        default: "GitHub Actions"
      usingEmoji:
        description: "Use emoji?"
        required: false
        default: y

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Pre-Main-Post (usingEmoji: inputs)'
        uses: ./.github/actions/pre-main-post
        with:
          usingEmoji: ${{ github.event.inputs.usingEmoji }}

      - name: 'Pre-Main-Post (usingEmoji: true)'
        uses: ./.github/actions/pre-main-post
        with:
          usingEmoji: true

      - name: 'Pre-Main-Post (usingEmoji: True)'
        uses: ./.github/actions/pre-main-post
        with:
          usingEmoji: True

      - name: 'Pre-Main-Post (usingEmoji: yes)'
        uses: ./.github/actions/pre-main-post
        with:
          usingEmoji: yes

      - name: 'Pre-Main-Post (usingEmoji: Yes)'
        uses: ./.github/actions/pre-main-post
        with:
          usingEmoji: Yes

      - name: 'Pre-Main-Post (usingEmoji: on)'
        uses: ./.github/actions/pre-main-post
        with:
          usingEmoji: on

      - name: 'Pre-Main-Post (usingEmoji: Ob)'
        uses: ./.github/actions/pre-main-post
        with:
          usingEmoji: On

      - name: 'Pre-Main-Post (usingEmoji: off)'
        uses: ./.github/actions/pre-main-post
        with:
          usingEmoji: off

      - name: 'Pre-Main-Post (usingEmoji: Off)'
        uses: ./.github/actions/pre-main-post
        with:
          usingEmoji: Off

      - name: 'Pre-Main-Post (usingEmoji: 1)'
        uses: ./.github/actions/pre-main-post
        with:
          usingEmoji: 1

      - name: 'Pre-Main-Post (usingEmoji: 0)'
        uses: ./.github/actions/pre-main-post
        with:
          usingEmoji: 0

      - name: "Pre-Main-Post (usingEmoji: '')"
        uses: ./.github/actions/pre-main-post
        with:
          usingEmoji: ''

      - name: 'Pre-Main-Post (usingEmoji: null)'
        uses: ./.github/actions/pre-main-post
        with:
          usingEmoji: null

      - name: Greet
        run: echo "Hello ${{ github.event.inputs.name }}!"

      - name: Greet with emoji
        if: ${{ github.event.inputs.usingEmoji }}
        run: echo "👋 ${{ github.event.inputs.name }}!"
