name: Weird boolean in GitHub Actions

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      boolValue:
        description: "Use emoji?"
        required: false
        default: y

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'boolValue: ${{ github.event.inputs.boolValue }}'
        if: ${{ github.event.inputs.boolValue != null }}
        uses: ./.github/actions/pre-main-post
        with:
          boolValue: ${{ github.event.inputs.boolValue }}

      - name: 'boolValue: true'
        uses: ./.github/actions/pre-main-post
        with:
          boolValue: true

      - name: 'boolValue: false'
        uses: ./.github/actions/pre-main-post
        with:
          boolValue: false

      - name: 'boolValue: True'
        uses: ./.github/actions/pre-main-post
        with:
          boolValue: True

      - name: 'boolValue: yes'
        uses: ./.github/actions/pre-main-post
        with:
          boolValue: yes

      - name: 'boolValue: Yes'
        uses: ./.github/actions/pre-main-post
        with:
          boolValue: Yes

      - name: 'boolValue: on'
        uses: ./.github/actions/pre-main-post
        with:
          boolValue: on

      - name: 'boolValue: On'
        uses: ./.github/actions/pre-main-post
        with:
          boolValue: On

      - name: 'boolValue: off'
        uses: ./.github/actions/pre-main-post
        with:
          boolValue: off

      - name: 'boolValue: Off'
        uses: ./.github/actions/pre-main-post
        with:
          boolValue: Off

      - name: 'boolValue: 1'
        uses: ./.github/actions/pre-main-post
        with:
          boolValue: 1

      - name: 'boolValue: 0'
        uses: ./.github/actions/pre-main-post
        with:
          boolValue: 0

      - name: "boolValue: ''"
        uses: ./.github/actions/pre-main-post
        with:
          boolValue: ''

      - name: 'boolValue: null'
        uses: ./.github/actions/pre-main-post
        with:
          boolValue: null

